### ISSUE TITLE
Cellpose error when training

### ISSUE THREAD

**Issue by Eddymorphling** [HenriquesLab/ZeroCostDL4Mic#164]
Hi folks,
I tried using the Cellpose-ZeroCostDL notebook to train and segment cells on some of my datasets. My source and target images are TIFF file format as mentioned in the description of the notebook. I come acroos this error message in Section 4.2. Any suggestions on how I can fix this? Thank you. 

```
>>>> !NEW LOGGING SETUP! To see cellpose progress, set --verbose
No --verbose => no progress or info printed
Not all flows are present. Run flow generation again.
Not all flows are present. Run flow generation again.
  0% 0/23 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/scipy/ndimage/measurements.py:1359: RuntimeWarning: invalid value encountered in true_divide
  for dir in range(input.ndim)]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 455, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 434, in main
    batch_size=args.batch_size, omni=args.omni)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/models.py", line 849, in train
    train_flows = dynamics.labels_to_flows(train_labels, files=train_files, use_gpu=self.gpu, device=self.device, omni=omni)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 607, in labels_to_flows
    labels, dist, heat, veci = map(list,zip(*[masks_to_flows(labels[n][0],use_gpu=use_gpu, device=device, omni=omni) for n in trange(nimg)]))
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 607, in <listcomp>
    labels, dist, heat, veci = map(list,zip(*[masks_to_flows(labels[n][0],use_gpu=use_gpu, device=device, omni=omni) for n in trange(nimg)]))
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 569, in masks_to_flows
    mu, T = masks_to_flows_device(masks, device=device)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 320, in masks_to_flows_gpu
    valid = masks_padded[centers[:,0], centers[:,1]] == np.arange(1, masks_padded.max()+1)
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 402
  0% 0/23 [00:00<?, ?it/s]
!! WARNING: Model folder already exists and has been removed !!
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-618b1fe7f0df> in <module>()
     45   print(bcolors.WARNING +"!! WARNING: Model folder already exists and has been removed !!" + W)
     46   shutil.rmtree(model_path+'/'+model_name)
---> 47 destination = shutil.copytree(Saving_path+"/train_folder/models", model_path+"/"+model_name)
     48 
     49 # Displaying the time elapsed for training

/usr/lib/python3.7/shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    316 
    317     """
--> 318     names = os.listdir(src)
    319     if ignore is not None:
    320         ignored_names = ignore(src, names)

FileNotFoundError: [Errno 2] No such file or directory: '/content/test/train_folder/models'
```

I did try to create a model folder under the directory mentioned above and re-ran 4.2. When I do this, the training finished in about 10 seconds (for a 50 epoch run) and I get the message below. I don't think it ran the training to create a model file as I cant see a model file in the folder above.
```

>>>> !NEW LOGGING SETUP! To see cellpose progress, set --verbose
No --verbose => no progress or info printed
Not all flows are present. Run flow generation again.
Not all flows are present. Run flow generation again.
  0% 0/23 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/scipy/ndimage/measurements.py:1359: RuntimeWarning: invalid value encountered in true_divide
  for dir in range(input.ndim)]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 455, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 434, in main
    batch_size=args.batch_size, omni=args.omni)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/models.py", line 849, in train
    train_flows = dynamics.labels_to_flows(train_labels, files=train_files, use_gpu=self.gpu, device=self.device, omni=omni)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 607, in labels_to_flows
    labels, dist, heat, veci = map(list,zip(*[masks_to_flows(labels[n][0],use_gpu=use_gpu, device=device, omni=omni) for n in trange(nimg)]))
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 607, in <listcomp>
    labels, dist, heat, veci = map(list,zip(*[masks_to_flows(labels[n][0],use_gpu=use_gpu, device=device, omni=omni) for n in trange(nimg)]))
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 569, in masks_to_flows
    mu, T = masks_to_flows_device(masks, device=device)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/dynamics.py", line 320, in masks_to_flows_gpu
    valid = masks_padded[centers[:,0], centers[:,1]] == np.arange(1, masks_padded.max()+1)
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 402
  0% 0/23 [00:00<?, ?it/s]
!! WARNING: Model folder already exists and has been removed !!
Time elapsed: 0.0 hour(s) 0.0 min(s) 11 sec(s)
Your model is also available here: /content/gdrive/MyDrive/Machine_Learning/Cellpose/Models/test
```

**Comment by pr4deepr** [comment]
How many training images do you have?

After section 4, can you create a code column and just check the value of:
Image_for_validation

If the value is zero, then is probably because you have less than 10 training images. 
If so, add more training images or as a workaround for now, you can add this code:

```
if Image_for_validation <=0:
  Image_for_validation =1
```

**Comment by Eddymorphling** [comment]
Thanks @pr4deepr . Going to close this now. We found out that the issue was with the way the label images were created.

**Comment by CisnerosFernandez** [comment]
Hello, 

I am getting a very similar error:

>>>> !NEW LOGGING SETUP! To see cellpose progress, set --verbose
No --verbose => no progress or info printed
Not all flows are present. Run flow generation again.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 458, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/cellpose/__main__.py", line 366, in main
    output = io.load_train_test_data(args.dir, test_dir, imf, args.mask_filter, args.unet, args.look_one_level_down)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/io.py", line 189, in load_train_test_data
    image_names_test = get_image_files(test_dir, mask_filter, image_filter, look_one_level_down)
  File "/usr/local/lib/python3.7/dist-packages/cellpose/io.py", line 129, in get_image_files
    raise ValueError('ERROR: no images in --dir folder')
ValueError: ERROR: no images in --dir folder
!! WARNING: Model folder already exists and has been removed !!
Time elapsed: 0.0 hour(s) 0.0 min(s) 39 sec(s)
Your model is also available here: /content/gdrive/MyDrive/Gant/Fig. 4 How do the senescent cells affect tissue regeneration/Immuno spatial/Settingup/Segmentar/Cellpose/model/model2

Could I ask how do you create the labelled images @Eddymorphling, I make them using the plugin ROI Maps from LOCI?

Thanks, 

Andrés

**Comment by pr4deepr** [comment]
Did you try updating cellpose? The new version comes with a lot of fixes..

**Comment by CisnerosFernandez** [comment]
> 
Yes I had the last version of cellpose. I realized that in my case the error was due to the fact that I was just trying to run all the script and had too little training pictures (less than ten). 

I also noticed that for me the script worked with less issues using source images in RGB format. 

Thank you very much.
