### ISSUE TITLE
Label-free prediction (fnet) 2D error when setting training parameters

### ISSUE THREAD

**Issue by HuiZhang0** [HenriquesLab/ZeroCostDL4Mic#192]
Hello,
I tried to train a model using Label-free prediction (fnet) 2D notebook but was faced with one error as shown in the photo.
![image](https://user-images.githubusercontent.com/105885505/169398259-4b5b5c49-dfbb-49d6-aac0-55ca90e18e11.png)

Thanks
Hui Zhang

**Comment by esgomezm** [comment]
Dear @HuiZhang0 
Can you please try it now and see if it works? Thank you!

**Comment by nrsid** [comment]
Hi,
I have many errors coming up. The first one is:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchdata 0.7.1 requires torch>=2, but you have torch 1.11.0+cu113 which is incompatible.
torchtext 0.17.1 requires torch==2.2.1, but you have torch 1.11.0+cu113 which is incompatible.

Is this a serious issue?
Thank you,
Siddharth

**Comment by IvanHCenalmor** [comment]
Dear @nrsid,

First of all, thank you very much for using fnet_2D. Sorry for the error you are getting, seems like there is a problems with the packages versions. Not a serious problem in principle, but it may create some issues so is better to fix it.  I have a version of the fnet_2D notebook, where after testing, seems that this problem is solved.

As you say that you are encountering many errors, I have uploaded it to copy of the ZeroCostDL4Mic repository on my profile. Like this, we can fix as many issues as we want in this repository and update the final working version to the official ZeroCostDL4Mic repository 🤗  Here it is the link to the updated notebook on Colab 👉  [https://colab.research.google.com/github/IvanHCenalmor/ZeroCostDL4Mic/blob/master/Colab_notebooks/fnet_2D_ZeroCostDL4Mic.ipynb](https://colab.research.google.com/github/IvanHCenalmor/ZeroCostDL4Mic/blob/master/Colab_notebooks/fnet_2D_ZeroCostDL4Mic.ipynb#scrollTo=btZhzA1oswmW)

Please try to use that notebook and tell us if previous issue is also solved for you. Also, it would be amazing if you can continue using the notebook and giving us feedback of any problem you encounter or if everything is correctly working.

When we are sure that everything is perfectly running we can update the updated version on the official ZeroCostDL4Mic repository so that everyone can continue using it and will also help to fix its version on DL4MicEveryhwere.

Thank you very much Siddharth for all your feedback! 🤗 

Please keep us updated of how does it work!
Iván

**Comment by nrsid** [comment]
Hi Ivan,

Thank you for the fix. 

I have now the following error:
after using your updated code:
This error starts during the training process.

I think the new tiff reader has some changes which is incompatible with the old tiff reader. A class is missing probably.

Do you have fix for this problem?

Thank you,
Siddharth

Lets start the training!
Traceback (most recent call last):
  File "/content/pytorch_fnet/train_model.py", line 2, in <module>
    import fnet.data
  File "/content/pytorch_fnet/fnet/data/__init__.py", line 1, in <module>
    from fnet.data.czidataset import CziDataset
  File "/content/pytorch_fnet/fnet/data/czidataset.py", line 2, in <module>
    from fnet.data.czireader import CziReader
  File "/content/pytorch_fnet/fnet/data/czireader.py", line 1, in <module>
    import aicsimage.io as io
  File "/content/pytorch_fnet/aicsimage/io/__init__.py", line 1, in <module>
    from . import cziReader
  File "/content/pytorch_fnet/aicsimage/io/cziReader.py", line 1, in <module>
    from . import czifile
  File "/content/pytorch_fnet/aicsimage/io/czifile.py", line 119, in <module>
    from tifffile.tifffile import FileHandle, decode_lzw, lazyattr, stripnull
ImportError: cannot import name 'decode_lzw' from 'tifffile.tifffile' (/usr/local/lib/python3.10/dist-packages/tifffile/tifffile.py)
Time elapsed: 0.0 hour(s) 0.0 min(s) 1 sec(s)
