### ISSUE TITLE
Error when loading pretrained stardist model in fiji

### ISSUE THREAD

**Issue by CelineNicky** [HenriquesLab/ZeroCostDL4Mic#236]
Hey everyone,
I used the Google colab to train my own stardist 2D model. However, when I try to load it into Fiji I get an error (see below). Can anyone help me out?
Thanks in advance! 

[INFO] Using native TensorFlow version: TF 1.14.0 CPU
[INFO] Loading TensorFlow model GenericNetwork_01c6b9f5d4274a55097a6ff55afd6a05 from source file file:/D:/Celine%20Training%20pictures/Staining%20Inim/20x/Stardist%20file/TF_SavedModel.zip
[INFO] Caching TensorFlow models to C:\Users\celin\DOCUME~1\Fiji\Fiji.app\models
java.lang.IllegalArgumentException: NodeDef mentions attr ‘allowed_devices’ not in Op<name=VarHandleOp; signature= → resource:resource; attr=container:string,default=“”; attr=shared_name:string,default=“”; attr=dtype:type; attr=shape:shape; is_stateful=true>; NodeDef: {{node down_level_0_no_0/kernel}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
[[down_level_0_no_0/kernel]]
at org.tensorflow.SavedModelBundle.load(Native Method)
at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
at net.imagej.tensorflow.CachedModelBundle.(CachedModelBundle.java:44)
at net.imagej.tensorflow.DefaultTensorFlowService.loadCachedModel(DefaultTensorFlowService.java:135)
at de.csbdresden.csbdeep.network.model.tensorflow.TensorFlowNetwork.loadModel(TensorFlowNetwork.java:163)
at de.csbdresden.csbdeep.network.model.DefaultNetwork.loadModel(DefaultNetwork.java:76)
at de.csbdresden.csbdeep.network.DefaultModelLoader.loadNetwork(DefaultModelLoader.java:69)
at de.csbdresden.csbdeep.network.DefaultModelLoader.run(DefaultModelLoader.java:48)
at de.csbdresden.csbdeep.commands.GenericCoreNetwork.tryToPrepareInputAndNetwork(GenericCoreNetwork.java:524)
at de.csbdresden.csbdeep.commands.GenericCoreNetwork.initiateModelIfNeeded(GenericCoreNetwork.java:303)
at de.csbdresden.csbdeep.commands.GenericCoreNetwork.mainThread(GenericCoreNetwork.java:445)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
[INFO] CSBDeep plugin exit (took 186 milliseconds)

**Comment by guijacquemet** [comment]
Hi @CelineNicky 
At the moment, the exported models are not compatible with the StarDist Fiji plugin. This is due to the fact that Fiji does not support TensorFlow 2.5.
If you would like to use the model you train with our notebook in Fiji, you will have to convert them first as described here:
https://gist.github.com/uschmidt83/4b747862fe307044c722d6d1009f6183

I hope this helps

Guillaume

**Comment by CelineNicky** [comment]
Hi @guijacquemet,
Do I need to convert the whole zip.file generated by the notebook? Sorry, I am very inexperienced with coding and keep getting the error that the config file doesn't exist in the map I selected even though the Zip.file with the code is present in this map. 
Any ideas?

**Comment by guijacquemet** [comment]
Hi @CelineNicky 
You need to download the whole model folder created by the Zerocostdl4mic notebook (not just the .Zip file).
Then locally, you can load your trained model using the code below.
In this case "model_name" should be replaced by the name you gave your model.
"model_path" is the path to the folder that contains your model folder. Does that help?

from stardist.models import StarDist2D
model = StarDist2D(None, name=model_name, basedir=model_path)
model.export_TF()

**Comment by CelineNicky** [comment]
Hi @guijacquemet 
Thanks so much!

**Comment by guijacquemet** [comment]
I am now closing this issue. Let us know if you still have problems!
