### ISSUE TITLE
StarDist 2D - Fiji not working on Fiji

### ISSUE THREAD

**Issue by lguerard** [HenriquesLab/ZeroCostDL4Mic#27]
Hi all,

I'm trying to use the notebook to train a StarDist model to use on Fiji. Training the model works and then I export it, save the zip file and use that in Fiji.

However, this is failing everytime and I'm getting

```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 1616MB of 185000MB (<1%)

 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.NullPointerException
	at de.csbdresden.stardist.StarDist2D.splitPrediction(StarDist2D.java:338)
	at de.csbdresden.stardist.StarDist2D.run(StarDist2D.java:307)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```
Any ideas ?

Thanks.

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out !
Is the Stardist plugin running fine with the pre-trained model provided in the plugin?
Also what version of tensorflow are you using in Fiji?

Cheers

Guillaume

**Comment by lguerard** [comment]
Hi,
Thanks for the fast answer !
No, it seems that it's not working either for the pre-trained model, maybe I should have checked that before. I don't know why though.
The Fiji tensorflow is 1.12.

Best,
Laurent

**Comment by guijacquemet** [comment]
Hi,
Happy to help. I looks like this is an issue with the Fiji plugin itself though so maybe you could contact them directly and see if they can help you out.
However, if you want to use the model trained in Colab you also need to change the Fiji tensorflow version.
 You can check at: Edit-- Options-- Tensorflow. Choose the version 1.13.1 (CPU or GPU depending on your system). The version 1.14 should also work.

**Comment by lguerard** [comment]
Hi,
I actually managed to solve it, it's something to do with the StarDist Fiji pluging indeed, it seems that it requires the Fiji updater which we had removed.

However, now Fiji crashed without any logs/messages when running the model. I don't exactly know if this should happen even with 100% CPU...

**Comment by guijacquemet** [comment]
Hi,
Do you have the correct version of Tensorflow installed?
You should Choose the version 1.13.1 (CPU or GPU depending on your system). The version 1.14 should also work.

**Comment by lguerard** [comment]
Hi,

Yes, sorry I didn't specify this in my previous message but I changed to 1.13.1 CPU. 

But maybe that's something I should talk with the StarDist people no ?

**Comment by guijacquemet** [comment]
If you cannot run the pre-trained model that they provide yes!
You can also try the 1.14 CPU
Cheers

**Comment by lguerard** [comment]
The pre-trained model works, the newly trained model works as well on small data but crashed on large ones without a log so I have no idea where it's coming from..

Best.

**Comment by guijacquemet** [comment]
Hi, 

Difficult to know for sure. Hopefully the Stardist team can help you out!

Cheers

G

**Comment by uschmidt83** [comment]
> the newly trained model works as well on small data but crashed on large ones without a log

What do you mean by "large"? Have you tried increasing the number of tiles for the StarDist prediction?

**Comment by lguerard** [comment]
Hi @uschmidt83 

Somehow the plugin calculated the tiles to use and started and failed using 12. When entering the value of 12 in the GUI somehow makes it work.

Thanks a lot !

**Comment by todd-fallesen** [comment]
I'm getting an almost identical error message: 
`(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 136MB of 12131MB (1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.NullPointerException
	at io.scif.services.DefaultInitializeService.initializeReader(DefaultInitializeService.java:87)
	at io.scif.img.ImgOpener.createReader(ImgOpener.java:483)
	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:242)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:152)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:133)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:138)
	at io.scif.convert.FileToDatasetConverter.convert(FileToDatasetConverter.java:66)
	at org.scijava.convert.AbstractConvertService.convert(AbstractConvertService.java:125)
	at org.scijava.convert.AbstractDelegateConverter.convert(AbstractDelegateConverter.java:53)
	at org.scijava.convert.AbstractConvertService.convert(AbstractConvertService.java:125)
	at org.scijava.module.DefaultModuleService.load(DefaultModuleService.java:316)
	at org.scijava.module.DefaultModuleService.loadInput(DefaultModuleService.java:544)
	at org.scijava.module.DefaultModuleService.lambda$loadInputs$1(DefaultModuleService.java:346)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.scijava.module.DefaultModuleService.loadInputs(DefaultModuleService.java:346)
	at org.scijava.module.process.LoadInputsPreprocessor.process(LoadInputsPreprocessor.java:58)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:154)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more'

This is on a fresh FIJI install with just downloading csbdeep and stardist, and just trying to open the plugin.  The plugin was working two days ago, oddly enough.

`
